### ISSUE TITLE
A minor typo

### ISSUE THREAD

**Issue by VainF** [NVlabs/DeepInversion#1]
This work is amazing! The generated images are so realistic!

[line 156 in imagenet_inversion.py](https://github.com/NVlabs/DeepInversion/blob/master/imagenet_inversion.py#L156) 
```python
parameters["store_best_images"] = self.store_best_images
```
=>

```python
parameters["store_best_images"] = args.store_best_images
```

**Comment by pamolchanov** [comment]
Thanks Gongfan, I hoped this typo did come to the main branch, will fix it
today, thanks for pointing.

Pavlo

**Comment by pamolchanov** [comment]
fixed
