### ISSUE TITLE
Are there any plans for sharing KD protocoll?

### ISSUE THREAD

**Issue by tjdhg456** [NVlabs/DeepInversion#18]
Thank you for sharing your great works.

Are there any additional plans for sharing the code for student training using KD (CIFAR or ImageNEt ..)

Thank you,.

**Comment by hongxuyin** [comment]
Hi thanks for feedback and we will see viability to release this in the next iteration. Will keep this thread updated.

**Comment by tjdhg456** [comment]
Thank you!!
