### ISSUE TITLE
The style of the generated images

### ISSUE THREAD

**Issue by MeLonJ10** [NVlabs/DeepInversion#8]
Hi!
Thank you all so much for the significant work.
There is a question. Why are the generated images appear like Cartoons images (or with art style) rather than realistic image?
Are there any possible explanation?
Best.

**Comment by hongxuyin** [comment]
Hi, we indeed have a more detailed discussion on this in paper long version (https://arxiv.org/pdf/1912.08795.pdf), Section 5, at limitations, point 2.
